<?php
$authObject = new LoginController($this->c()); // This must be at the top ?>
<!DOCTYPE html>
<html>
    <head>
        <title>Software and Games Center - SGC</title>
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
        <link rel="stylesheet" type="text/css" href="styles/style.css" />
        <link rel="stylesheet" type="text/css" href="styles/basket.css" />
        <link type="text/css" href="css/custom-theme/jquery-ui-1.8.18.custom.css" rel="stylesheet">
        <script src="http://code.jquery.com/jquery-1.7.1.min.js" type="text/javascript"></script>
         <script type="text/javascript" src="js/jquery-ui-1.8.18.custom.min.js"></script>
         <script type="text/javascript" src="./scripts/raphael-min.js"></script>
         <script type="text/javascript" src="./scripts/g.raphael-min.js"></script>
    </head>
    <body>
        <div id="main_container">    
            <div id="header">
                <div class="top_right">
                    <div class="big_banner">
                        <a href="#">
                            <OBJECT style="z-index: -1;" CLASSID="clsid:D27CDB6E-AE6D-11cf-96B8-444553540000"  CODEBASE="http://active.macromedia.com/flash5/cabs/swflash.cab#version=5,0,0,0">
                            	<PARAM NAME="MOVIE" VALUE="./images/BANNER2.swf">
                            	<PARAM NAME="PLAY" VALUE="true">
                            	<PARAM NAME="LOOP" VALUE="true">
                            	<PARAM NAME="QUALITY" VALUE="high">
                            	<PARAM NAME="SCALE" value="noborder">
                            	<EMBED SRC="./images/BANNER2.swf" wmode="transparent"  WIDTH="728px" HEIGHT="128px" PLAY="true"  LOOP="true" QUALITY="high"  scale="noborder" PLUGINSPAGE="http://www.macromedia.com/shockwave/download/index.cgi?P1_Prod_Version=ShockwaveFlash"> </EMBED>
                            </OBJECT>
                        </a>
                    </div>
                </div>
        
                <div id="logo">
                    <a href="./?c=Index"><img class="site-logo" src="images/CD-earth.png" alt="SGC" title="SGC" border="0" /></a>
        	    </div>
                
                <div id="basket-container">
                    <?php $this->includeController('ShoppingCart', array()); ?>
                </div>
                
            </div>
        
            <div id="main_content"> 
       
                <div id="menu_tab">
                        <ul class="menu">
                        <li><a href="./?c=Index" class="nav">  Home </a></li>
                        <li class="divider"></li>
                        <li><a href="./?c=Games" class="nav">Games</a></li>
                        <li class="divider"></li>
                        <li><a href="./?c=Software" class="nav">Software</a></li>


                        <li class="divider"></li>
                        <?php if (!$authObject->getAuthenticated()): ?>
                            <li><a href="#" id="register" class="nav right">Register</a></li>
                            <li><a href="#" id="login" class="nav right">Log In</a></li>
                        <?php else: ?>
                        	<?php if ($authObject->getLoginInformation()->getTag('access-level') !== AccessLevels::ANYONE): ?>
                        	<li><a href="./?c=BackOffice" class="nav right">Staff</a></li>
                        	<?php else:?>
                            <li><a href="#" onclick="alert('Need to Implement an account screen, remove this when implemented'); //REMOVE ONCLICK STUFF ON IMPLEMENTATION" class="nav right">My Account</a></li>
                            <li><a class="nav right" href="#" id="basket-button">Basket</a></li>
                            <?php endif;?>
                            <li><a class="nav right" href="./?c=Login&logout<?php  echo ($this->c() !== NULL)? '&go-to=' . $this->c() : '&go-to=Index' ; ?>">Log out</a></li>
                        <?php endif; ?>
                    </ul>
                    <div class="search">
                            <form action="./?c=Search" method="GET">
                                <input type="hidden" name="c" value="Search" />
                                <input type="text" name="q" id="q" class="text ui-widget-content ui-corner-all"/> 
                                <input type="submit" value="Search"/>
                                </form>
                            </div>
                </div><!-- end of menu tab -->    
            </div><!-- end of main content --> 
        
            <div class="center_content">
            
            
                <?php $this->content(); ?>
                
                
            </div>
            
            <div class="footer">
                <div class="left_footer">
                    <img src="images/footer_logo.png" alt="" title="" width="89" height="42"/>
                </div>
                <div class="center_footer">
                    <p>. All Rights Reserved 2012</p>
                    <img src="images/payment.gif" alt="" title="" />
                </div>
            
                <div class="right_footer">
                    <a href="./?c=Index">home</a>
                </div>   
            </div>                 
        </div>
        <?php if (!$authObject->getAuthenticated()): ?>
            <div id="login-box" title="Log In">
                    <?php 
                        $loginView = new View($authObject); 
                       $loginView->render();
                   ?>
            </div>
            <div id="register-box">
                <?php $this->includeController('Register', array()); ?>
             </div>
             <div id="please-login" class="hidden">
             <p>Log in or Register to start shopping!</p>
             </div>
        <?php endif; ?>

            <div id="mask"></div>
</div>
<script src="scripts/basket.js" type="text/javascript"></script> <!-- Methods in here "Ajaxify" basket links so the page isn't reloaded on links that are clicked to add to basket-->
    <script src="scripts/registration.js" type="text/javascript"></script>
<!-- end of main_container -->
    <script type="text/javascript">
      $(document).ready(function() {
          
          $("#login").click(function(e){
               e.preventDefault();
                //Get the A tag
               $('#login-box').dialog("open");
           });
          
          $('#login-box').dialog({
    		autoOpen: false,
            modal: true
          });
          
    $('a.add-to-basket').click(function(e) {
        <?php if($authObject->getAuthenticated()):?>
        $('#basket-button').click();
        <?php else: ?>
        $('#please-login').dialog({modal: true,
    		buttons: {
				Ok: function() {
					$( this ).dialog( "close" );
				}
			}});
        <?php endif; ?>
        return false;
        });
        
    $('#basket-button').click(function(e) {
        $('#basket-container').dialog({
            width: 320,
            minWidth: 320
            });
        
        });
    
        $("input:submit").button();		
		$("#register-form").dialog(registrationDialog);
        $("#register").click(function(e) {
            $( "#register-form" ).dialog( "open" );    
        });
          
          
          });
    </script>  
  </body>
</html>