<?php 
/**
 * A simple page that links to different BackOffice pages.
 * @author Samuel Giles
 * @package application-views
 * @subpackage application-views-content
 * @version 1.0
 */
?>
<a href="./?c=ListProducts" class="prod_buy"> List Products</a>
<a href="./?c=Staff" class="prod_buy"> Staff</a>
<a href="./?c=Customer" class="prod_buy"> Customers</a>
<a href="./?c=Order" class="prod_buy"> Order</a>
<a href="./?c=Wholesaler" class="prod_buy"> Wholesalers</a>