<a href="./?c=ListProducts" class="prod_buy"> List Products</a>
<a href="./?c=Staff" class="prod_buy"> Staff</a>
<a href="./?c=Customer" class="prod_buy"> Customers</a>
<a href="./?c=Order" class="prod_buy"> Order</a>
<a href="./?c=Wholesaler" class="prod_buy"> Wholesalers</a>




<a href="./?c=ListProducts">List Products</a>
<a href="./?c=Staff">Staff</a>
<a href="./?c=Customer">Customers</a>
<a href="./?c=Order">Order</a>
<a href="./?c=Wholesaler">Wholesalers</a>