<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=windows-1252" />
<title>Tools Shop</title>
<link rel="stylesheet" type="text/css" href="style.css" />
<!--[if IE 6]>
<link rel="stylesheet" type="text/css" href="iecss.css" />
<![endif]-->
<script type="text/javascript" src="js/boxOver.js"></script>
</head>
<body>

<div id="main_container">

    <div id="header">

       <div class="top_right">
         <div class="big_banner">
           <a href="#"><img src="images/banner728.jpg" alt="" title="" border="0" /></a>
           </div>
        
        </div>
    
  
        <div id="logo">
            <a href="index.html"><img src="images/logo.png" alt="" title="" border="0" width="182" height="85" /></a>
	    </div>
        

        

    </div>
    
   <div id="main_content"> 
   
            <div id="menu_tab">
                    <ul class="menu">
                         <li><a href="index.html" class="nav">  Home </a></li>
                         <li class="divider"></li>
                         <li><a href="#" class="nav">Products</a></li>
                         <li class="divider"></li>
                         <li><a href="#" class="nav">About Us</a></li>
                         <li class="divider"></li>
                         <li><a href="contact.html" class="nav">Contact Us</a></li>

                    </ul>

            </div><!-- end of menu tab -->
            
    
    
    </div><!-- end of left content --> 



<div class="center_content">
   
   
   	<div class="center_title_bar"><center>Your order has now been placed!</center></div>
    <center>Thank you for shopping with Software & Games Centre</center>
    	
</div><!-- end of center content --><!-- end of right content -->   


            
   </div><!-- end of main content -->
   
   
   
   <div class="footer">
   

        <div class="left_footer">
        <img src="images/footer_logo.png" alt="" title="" width="89" height="42"/>
        </div>
        
        <div class="center_footer">
        Comapany name . All Rights Reserved 2012<br />
        <br />
        <img src="images/payment.gif" alt="" title="" />
        </div>
        
        <div class="right_footer">
        <a href="index.html">home</a>
        <a href="products.html">products</a>
        <a href="products.html">about us</a>
        <a href="contact.html">contact us</a>
        </div>   
   
   </div>                 


</div>
<!-- end of main_container -->
</body>
</html>