<?php 
/**
 * Backoffice template for creating a sales order.
 * @author Nadeem Alam
 * @package application-views-content
 */
?>
<h1> CUSTOMER DETAILS</H1>
<style>
#txtChar{width:25}
</style>

<form>

<form name="input" action="html_form_action.asp" method="get">
<label><big>Customer Code:</big></label>
<input type="text" code="customercode" /><br /> 
<label><big>First name:</big></label> 
<input type="text" name="firstname" /><br />
<label><big>Last name:</big></label> 
<input type="text" name="lastname" /><br /> 
<label><big>Post Code:</big></label> 
<input type="text" postcode="postcode" /><br />
<input type="submit" value="Search" /><br />
</form> 

<H1> PRODUCT DETAILS </H2>
<form>
<label><big> Product Code: </big></label>
<input type="text" code="productcode" /></br    />

<label><big> Product Description: </big></label>
<div id="panel">
  <div id="field_name">TEXT GOES HERE</div>
</div></br  />

<SCRIPT language=Javascript>
      <!--
      function isNumberKey(evt)
      {
         var charCode = (evt.which) ? evt.which : event.keyCode
         if (charCode > 31 && (charCode < 48 || charCode > 57))
            return false;

         return true;
      }
      //-->
   </SCRIPT>
   </HEAD>
   <BODY>
     QTY:<INPUT id="txtChar" onkeypress="return isNumberKey(event)" type="text" name="txtChar">
   </BODY>
   <br  />
   
<H1> PAYMENT DETAILS </H1>
<form>
<label><big>Name on Card:</big></label>
<input type="text" name="cardname" /><br   />
<SCRIPT language=Javascript>
      <!--
      function isNumberKey(evt)
      {
         var charCode = (evt.which) ? evt.which : event.keyCode
         if (charCode > 31 && (charCode < 48 || charCode > 57))
            return false;

         return true;
      }
      //-->
   </SCRIPT>
   </HEAD>
   <BODY>
     <big>Card Number:</big><INPUT id="cnumber" onkeypress="return isNumberKey(event)" type="text" name="txtChar">
   <big> Card Expiry Date </big>
   <input value = "26-03-2012" type="date" >
    
   </BODY> 
   <br  />
   
   
  