<?php 
/**
 * Backoffice template for creating a sales order.
 * @author Nadeem Alam
 * @package application-views-content
 */
?>
<h1> CUSTOMER DETAILS</H1>
<style>
#txtChar{width:25}
</style>

<form>

<form name="input" action="html_form_action.asp" method="get">
<label><big>Customer Code:</big></label>
<input type="text" code="customercode" /><br /> 
<label><big>First name:</big></label> 
<input type="text" name="firstname" /><br />
<label><big>Last name:</big></label> 
<input type="text" name="lastname" /><br /> 
<label><big>Post Code:</big></label> 
<input type="text" postcode="postcode" /><br />
<input type="submit" value="Search" /><br />
</form> 

<H1> PRODUCT DETAILS </H2>
<form>
<label><big> Product Code: </big></label>
<input type="text" code="productcode" /></br    />

<label><big> Product Description: </big></label>
<div id="panel">
  <div id="field_name">TEXT GOES HERE</div>
</div></br  />

<SCRIPT language=Javascript>
      <!--
      function isNumberKey(evt)
      {
         var charCode = (evt.which) ? evt.which : event.keyCode
         if (charCode > 31 && (charCode < 48 || charCode > 57))
            return false;

         return true;
      }
      //-->
   </SCRIPT>
   </HEAD>
   <BODY>
     QTY:<INPUT id="txtChar" onkeypress="return isNumberKey(event)" type="text" name="txtChar">
   </BODY>
   <br  />
   
<H1> PAYMENT DETAILS </H1>
<form>
<label><big>Name on Card:</big></label>
<input type="text" name="cardname" /><br   />
<SCRIPT language=Javascript>
      <!--
      function isNumberKey(evt)
      {
         var charCode = (evt.which) ? evt.which : event.keyCode
         if (charCode > 31 && (charCode < 48 || charCode > 57))
            return false;

         return true;
      }
      //-->
   </SCRIPT>
   </HEAD>
   <BODY>
     <big>Card Number:</big><INPUT id="cnumber" onkeypress="return isNumberKey(event)" type="text" name="txtChar">
   <big> Card Expiry number </big>
   <?php
      $myCalendar = new tc_calendar("date1", true);
	  $myCalendar->setIcon("calendar/images/iconCalendar.gif");
	  $myCalendar->setDate(01, 03, 1960);
	  $myCalendar->setPath("calendar/");
	  $myCalendar->setYearInterval(1960, 2015);
	  $myCalendar->dateAllow('1960-01-01', '2015-03-01');
	  $myCalendar->setSpecificDate(array("2011-04-01", "2011-04-13", "2011-04-25"), 0, 'month');
	  $myCalendar->setOnChange("myChanged('test')");
	  $myCalendar->writeScript();
	  ?>

<script language="javascript">
<!--
function myChanged(v){
	alert("Hello, value has been changed : "+document.getElementById("date1").value+"["+v+"]");
}
//-->
</script>
   </BODY> 
   <br  />
   
   
  