<?php 
/**
 * A screen for viewing and adding Customer
 * @author Vishal Patel
 * @package application-views
 * @subpackage application-views-content
 * @version 0.2
 */                
?>
<div id="users-contain" class="ui-widget">
    <h1>Customer:</h1>
    <table id="users" class="ui-widget ui-widget-content">
		<thead>
			<tr class="ui-widget-header ">
				<th>Code</th>
                <th>Username</th>
				<th>First Name</th>
                <th>Last Name</th>
                <th>Phone Number</th>
                <th>Email</th>
                <th>Line One</th>
                <th>Line Two</th>
                <th>Post Code</th>
			</tr>
		</thead>
		<tbody>
          <?php foreach ($this->Customer() as $Customer):?>
			<tr>
				<td><?php echo $Customer['CODE']; ?></td>
                <td><?php echo $Customer['USERNAME']; ?></td>
    			<td><?php echo $Customer['F_NAME']; ?></td>
                <td><?php echo $Customer['L_NAME']; ?></td>
                <td><?php echo $Customer['PHONE_NUMBER']; ?></td>
                <td><?php echo $Customer['EMAIL']; ?></td>
                <td><?php echo $Customer['LINE_ONE']; ?></td>
                <td><?php echo $Customer['LINE_TWO']; ?></td>
                <td><?php echo $Customer['POST_CODE']; ?></td>
                <td><button>Edit</button> <button>Delete</button></td>
                
			</tr>
          <?php endforeach; ?>
		</tbody>
	</table>
    <button id="create-Customer">Create new Customer</button>
</div>
<div id="Customer-form" title="Create New Customer User">
    <p class="validateCustomerTips">All form fields are required.</p>

	<form>
	<fieldset>
        <label for="Code">Code</label>
		<input type="text" code="Code" id="Code" class="text ui-widget-content ui-corner-all" />
        
        <label for="Username">Username</label>
		<input type="text" name="Username" id="Username" class="text ui-widget-content ui-corner-all" />
        
		<label for="First Name">First Name</label>
		<input type="text" name="First Name" id="First name" class="text ui-widget-content ui-corner-all" />
		
		<label for="Last Name">Last Name</label>
		<input type="text" name="Last Name" id="Last Name" class="text ui-widget-content ui-corner-all" />
        
        <label for="Phone Number">Phone Number</label>
		<input type="text" name="Phone Number" id="Phone Number" class="text ui-widget-content ui-corner-all" />
        
		<label for="Email">Email</label>
		<input type="text" name="Email" id="Email" value="" class="text ui-widget-content ui-corner-all" />
       
        <label for="Location">Location</label>
    	<input type="text" name="Location" id="Location" value="" class="text ui-widget-content ui-corner-all" />
        
        <label for="Line One">Line One</label>
    	<input type="text" name="Line One" id="Line One" value="" class="text ui-widget-content ui-corner-all" />
        
        <label for="Line Two">Line Two</label>
    	<input type="text" name="Line Two" id="Line Two" value="" class="text ui-widget-content ui-corner-all" />
        
        <label for="Postcode">Postcode</label>
        <input type="text" name="Post Code<" id="Post Code" value="" class="text ui-widget-content ui-corner-all" />
        
        <label for="Card Name">Card Name</label>
        <input type="text" name="Card Name" id="Card Name" value="" class="text ui-widget-content ui-corner-all" />
        
        <label for="Payment Account Number">Line Two</label>
    	<input type="text" name="Payment Account Number" id="Payment Account Number" value="" class="text ui-widget-content ui-corner-all" />
        
        <label for="Expiry Date">Expiry Date</label>
        <input type="text" name="Expiry Date<" id="Expiry Date" value="" class="text ui-widget-content ui-corner-all" />
        </fieldset>
	</form>
</div>