<?php 
/**
 * The index page content.
 * @author James Legros
 * @package application-views
 * @subpackage application-views-content
 * @version 1.0
 */

/*
 * Note:
 *  All views in the Content and Layout folders must be PHP fragment files.  I.e. They must have the file extension ".phtml"  For example "index.phtml".
 *  This is how the reference loads the views. - Sam
 */?>

<div class="oferta">
    <img src="images/prosmall.png" width="97" height="128" border="0" class="oferta_img" alt="" title="" />            	
    <div class="oferta_details">
    <div class="oferta_title">Windows 7</div>
    <div class="oferta_text"> Windows&nbsp;7&nbsp;Home Premium makes it easy to create a home network and share all of your favourite photos, videos, and music. You can even watch, pause, rewind, and record TV. Get the best entertainment experience with&nbsp;Windows&nbsp;7&nbsp;Home Premium. </div>
        <a href="./?c=Search&q=windows+7" class="prod_buy"> more details</a>
    </div>
</div>
   
<div class="center_title_bar">Latest Products</div>
    <?php $this->includeController('LatestProducts', array()); ?>
</div>