<?php 
/**
 * Used to output the login form if logged in and nothing if logged in.
 * TODO: Remove the redirect stuff, as this is simply being used as a hacky method of redirecting to another controller on successful login.
 * @author Samuel Giles
 * @package views/content
 */

 if ($this->redirect()) {
   header('Location: http://uni.myftp.org/WebApplication/core/?c=' . $this->redirect());
   exit(0);
 }
 
?>
<?php if (!$this->hasAuthenticated()): ?>
<div class="login-container">
  <form action="./?c=Login<?php 
        echo ($this->setRedirect() !== NULL)? '&go-to=' . $this->setRedirect() : '' ;
        ?>" method="POST">
        <fieldset>
     <label>Username:</label>
       <input type="test" name="uname" class="text ui-widget-content ui-corner-all"/>
     <label>Password:</label>
       <input type="password" name="pword" class="text ui-widget-content ui-corner-all"/>
       <input type="submit" value="Log in!" class="submit" />
       </fieldset>
  </form>
  <?php if ($this->invalidDetails()): ?>
   <p class="red">Invalid username or password</p>
  <?php endif;?>
  <a href="#">Forgotten your password?</a>
</div>
<? endif;