<?php 
/**
 * A simple registration form.
 * @author Samuel Giles
 * @package application-views-content
 */
?>
<div id="register-form" title="Register">
    <p class="validateTips">All form fields are required.</p>
	<form id="registration-form" method="POST" action="./?c=Register">
	<fieldset>
		<label for="fname">First Name</label>
		<input type="text" name="fname" id="fname" class="text ui-widget-content ui-corner-all" />
        <label for="lname">Last Name</label>
    	<input type="text" name="lname" id="lname" class="text ui-widget-content ui-corner-all" />
        <label for="email">Email</label>
		<input type="text" name="email" id="email" value="" class="text ui-widget-content ui-corner-all" />
        <label for="uname">Username</label>
    	<input type="text" name="uname" id="uname" class="text ui-widget-content ui-corner-all" />
		<label for="password">Password</label>
		<input type="password" name="password" id="password" value="" class="text ui-widget-content ui-corner-all" />
        <label for="rpassword">Repeat Password</label>
		<input type="password" name="rpassword" id="rpassword" value="" class="text ui-widget-content ui-corner-all" />
        
        <label for="addrlineone">Address Line One</label>
		<input type="text" name="addrlineone" id="addrlineone" class="text ui-widget-content ui-corner-all" />
        <label for="addrlinetwo">Address Line Two</label>
    	<input type="text" name="addrlinetwo" id="addrlinetwo" class="text ui-widget-content ui-corner-all" />
        <label for="postcode">Post Code</label>
    	<input type="text" name="postcode" id="postcode" class="text ui-widget-content ui-corner-all" />
	</fieldset>
	</form>
</div>