<?php 
/**
 * A simple stock check screen that will allow staff members to view stock items.
 * @author Nikolas Dimitriou
 * @package application-views
 * @subpackage application-views-content
 */
?>

<?php 
/**
 * A simple stock check screen that will allow staff members to view stock items.
 * @author Nikolas Dimitriou
 * @package application-views-content
 */
?>

<table border="1">
<tr>
<th>Serial Number </th>
<th>Software & Games(Products) </th>
<th>Quantity </th>
<th>Orders </th>
</tr>
<tr>
<td>240075</td>
<td>Microsoft Office 2010 Professional</td>
<td>16</td>
<td><input type="checkbox" name="Software" value="Game" /> <br /></td>
</tr>
<tr>
<td> </td>
<td> </td>
<td> </td>
<td><input type="checkbox" name="vehicle" value="Bike" /> <br /></td>
</tr>
<tr>
<td> </td>
<td> </td>
<td> </td>
<td><input type="checkbox" name="vehicle" value="Bike" /> <br /></td>
</tr>
<tr>
<td> </td>
<td> </td>
<td> </td>
<td><input type="checkbox" name="vehicle" value="Bike" /> <br /></td>
</tr>
<tr>
<td> </td>
<td> </td>
<td> </td>
<td><input type="checkbox" name="vehicle" value="Bike" /> <br /></td>
</tr>
<tr>
<td> </td>
<td> </td>
<td> </td>
<td><input type="checkbox" name="vehicle" value="Bike" /> <br /></td>
</tr>
<tr>
<td> </td>
<td> </td>
<td> </td>
<td><input type="checkbox" name="vehicle" value="Bike" /> <br /></td>
</tr>
<tr>
<td> </td>
<td> </td>
<td> </td>
<td><input type="checkbox" name="vehicle" value="Bike" /> <br /></td>
</tr>
<tr>
<td> </td>
<td> </td>
<td> </td>
<td><input type="checkbox" name="vehicle" value="Bike" /> <br /></td>
</tr>
<tr>
<td> </td>
<td> </td>
<td> </td>
<td><input type="checkbox" name="vehicle" value="Bike" /> <br /></td>
</tr>
<tr>
<td> </td>
<td> </td>
<td> </td>
<td><input type="checkbox" name="vehicle" value="Bike" /> <br /></td>
</tr>
<tr>
<td> </td>
<td> </td>
<td> </td>
<td><input type="checkbox" name="vehicle" value="Bike" /> <br /></td>
</tr>
<tr>
<td> </td>
<td> </td>
<td> </td>
<td><input type="checkbox" name="vehicle" value="Bike" /> <br /></td>
</tr>
</table>
<button type="button">Finish order!</button>
